#!/usr/bin/env bash
set -euo pipefail

SOURCE="${BASH_SOURCE[0]}"
while [[ -L "$SOURCE" ]]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
ICONFORGE_ROOT="$SCRIPT_DIR"

# shellcheck source=lib/iconforge/common.sh
source "$SCRIPT_DIR/lib/iconforge/common.sh"
# shellcheck source=lib/iconforge/config.sh
source "$SCRIPT_DIR/lib/iconforge/config.sh"
# shellcheck source=lib/iconforge/forge.sh
source "$SCRIPT_DIR/lib/iconforge/forge.sh"
# shellcheck source=lib/iconforge/library.sh
source "$SCRIPT_DIR/lib/iconforge/library.sh"
# shellcheck source=lib/iconforge/discovery.sh
source "$SCRIPT_DIR/lib/iconforge/discovery.sh"
# shellcheck source=lib/iconforge/match.sh
source "$SCRIPT_DIR/lib/iconforge/match.sh"
# shellcheck source=lib/iconforge/strategy-internal-icns.sh
source "$SCRIPT_DIR/lib/iconforge/strategy-internal-icns.sh"
# shellcheck source=lib/iconforge/strategy-native-icon.sh
source "$SCRIPT_DIR/lib/iconforge/strategy-native-icon.sh"
# shellcheck source=lib/iconforge/strategy.sh
source "$SCRIPT_DIR/lib/iconforge/strategy.sh"
# shellcheck source=lib/iconforge/apps.sh
source "$SCRIPT_DIR/lib/iconforge/apps.sh"
# shellcheck source=lib/iconforge/backend.sh
source "$SCRIPT_DIR/lib/iconforge/backend.sh"
# shellcheck source=lib/iconforge/cli.sh
source "$SCRIPT_DIR/lib/iconforge/cli.sh"
# shellcheck source=lib/iconforge/completion.sh
source "$SCRIPT_DIR/lib/iconforge/completion.sh"

root_help() {
  cat <<EOF_HELP
iconforge v$ICONFORGE_VERSION

Make icons at the forge. Keep them at the hearth. Apply them by name.

Usage:
  iconforge <command> [arguments] [options]
  iconforge <input-image> [output-name] [forge-options]

Commands:
  forge         Convert artwork into macOS .icns files
  config        Configure the-forge and the-hearth independently
  inspect       Explain an application's icon metadata
  apply         Apply an icon by app name, or explicitly select --all
  restore       Restore supported changes to an application
  refresh       Refresh current-user macOS icon caches
  nuke          Alias for refresh (also: apply Firefox nuke)
  doctor        Check configuration, helpers, and an optional app
  capabilities  Show implemented platform capabilities
  completion    Print shell completion for bash, zsh, or fish
  help          Show this overview or help for a command

Quick start:
  iconforge config set the-forge "\$HOME/icon-work"
  iconforge config set the-hearth "\$HOME/app-icons"
  iconforge apply Firefox --dry-run
  iconforge apply Firefox nuke
  iconforge apply --all --dry-run

Directories can be anywhere, or the same folder. Finished icons do not have to
be generated by IconForge. Legacy default-directory remains a fallback.

Command help: iconforge help apply
Image-first shorthand: iconforge logo.png BrandMark -o ./icons

Global options:
  -h, --help       Show this overview
  -v, --version    Show the Icon Forge version

Current backend: macOS app icons. Other platforms are not implemented.
Full reference: docs/CLI.md
EOF_HELP
}

is_supported_forge_path() {
  local input="${1:-}" extension=""
  [[ -f "$input" && ! -L "$input" ]] || return 1
  extension="$(printf '%s' "${input##*.}" | tr '[:upper:]' '[:lower:]')"
  case "$extension" in png|jpg|jpeg|webp|tiff|tif|gif) return 0 ;; esac
  return 1
}

cmd_help() {
  local topic="" topic_seen=false options_done=false
  while [[ $# -gt 0 ]]; do
    if [[ "$options_done" != true ]]; then
      case "$1" in
        --) options_done=true; shift; continue ;;
        -h|--help)
          [[ $# -eq 1 && "$topic_seen" != true ]] || { usage_fail 'Help cannot combine a topic with -h/--help'; return 2; }
          root_help; return 0 ;;
        -*) usage_fail "Unknown help flag: $1"; return 2 ;;
      esac
    fi
    [[ "$topic_seen" != true ]] || { usage_fail "Unexpected help argument: $1"; return 2; }
    [[ -n "$1" ]] || { usage_fail 'Help topic must not be empty'; return 2; }
    topic="$1"; topic_seen=true; shift
  done
  [[ "$topic_seen" == true ]] || { root_help; return 0; }
  case "$topic" in
    forge|config|inspect|apply|restore|nuke|refresh|doctor|capabilities|completion) dispatch_subcommand "$topic" --help ;;
    help) root_help ;;
    *) usage_fail "Unknown help topic: $topic"; return 2 ;;
  esac
}

dispatch_subcommand() {
  local command="$1"
  shift
  ICONFORGE_DRY_RUN=false
  case "$command" in
    help) cmd_help "$@" ;;
    forge) cli_forge "$@" ;;
    config) cmd_config "$@" ;;
    apply) cli_apply "$@" ;;
    inspect|restore|nuke|refresh) cli_target_command "$command" "$@" ;;
    doctor) cmd_doctor "$@" ;;
    capabilities) cmd_capabilities "$@" ;;
    completion) cmd_completion "$@" ;;
    *) usage_fail "Unknown command: $command"; return 2 ;;
  esac
}

main() {
  [[ $# -gt 0 ]] || { root_help; return 0; }
  case "$1" in
    -h|--help)
      [[ $# -eq 1 ]] || { usage_fail "$1 does not accept arguments"; return 2; }
      root_help ;;
    -v|--version)
      [[ $# -eq 1 ]] || { usage_fail "$1 does not accept arguments"; return 2; }
      printf 'iconforge v%s\n' "$ICONFORGE_VERSION" ;;
    --)
      shift
      [[ $# -gt 0 ]] || { usage_fail '-- requires a supported input image path'; return 2; }
      is_supported_forge_path "$1" || { usage_fail "Not a supported forge input: $1"; return 2; }
      cli_forge -- "$@" ;;
    -*) usage_fail "Unknown global flag: $1"; return 2 ;;
    *)
      case "$1" in
        forge|config|inspect|apply|restore|nuke|refresh|doctor|capabilities|completion|help) dispatch_subcommand "$@" ;;
        *)
          if is_supported_forge_path "$1"; then cli_forge "$@"; else usage_fail "Unknown command or unsupported input image: $1"; return 2; fi
          ;;
      esac
      ;;
  esac
}
main "$@"
